[[plugins]]
repo = "mattn/emmet-vim"
on_ft = ["javascript", "html"]

[[plugins]]
repo = "jason0x43/vim-js-indent"
on_ft = ["typescript", "javascript", "html"]

[[plugins]]
repo = "leafgarland/typescript-vim"
on_ft = ["typescript"]

[[plugins]]
repo = "cespare/vim-toml"
on_ft = ["toml"]

[[plugins]]
repo = "fatih/vim-go"
on_ft = ["go"]

[[plugins]]
repo = "eagletmt/ghcmod-vim"
on_ft = ["haskell"]

[[plugins]]
repo = "eagletmt/neco-ghc"
on_ft = ["haskell"]

[[plugins]]
repo = "itchyny/vim-haskell-indent"
on_ft = ["haskell"]

[[plugins]]
repo = "derekwyatt/vim-scala"
on_ft = ["scala"]
