[[plugins]]
repo = "nathanaelkane/vim-indent-guides"

[[plugins]]
repo = "Shougo/neocomplcache"

[[plugins]]
repo = "thinca/vim-quickrun"

[[plugins]]
repo = "yuroyoro/vimdoc_ja"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "scrooloose/nerdcommenter"

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "ctrlpvim/ctrlp.vim"

[[plugins]]
repo = "godlygeek/tabular"

[[plugins]]
repo = "plasticboy/vim-markdown"

[[plugins]]
repo = "kannokanno/previm"

[[plugins]]
repo = "tyru/open-browser.vim"

[[plugins]]
repo = "flazz/vim-colorschemes"

[[plugins]]
repo = "h1mesuke/vim-alignta"

[[plugins]]
repo = "kana/vim-operator-user"

[[plugins]]
repo = "kana/vim-textobj-user"

[[plugins]]
repo = "rhysd/vim-operator-surround"

[[plugins]]
repo = "osyo-manga/vim-textobj-multiblock"

[[plugins]]
repo = "Townk/vim-autoclose"

[[plugins]]
repo = "scrooloose/nerdtree"

[[plugins]]
repo = "csscomb/vim-csscomb"

[[plugins]]
repo = "haya14busa/incsearch.vim"

[[plugins]]
repo = "scrooloose/syntastic"

[[plugins]]
repo = "editorconfig/editorconfig-vim"

[[plugins]]
repo = "Shougo/vimproc"
build = "make"

[[plugins]]
repo = "fuenor/JpFormat.vim"

[[plugins]]
repo = "wakatime/vim-wakatime"

[[plugins]]
repo = "kylef/apiblueprint.vim"
