update
upgrade

install docker
install boot2docker
install git
install tig
install iperf
install nkf
install tag
install wget
install rbenv
install fish
install scala
install play
install node
install imagemagick
install haskell-platform
install mono
install hub
install unrar
install pandoc

tap phinze/cask
install brew-cask

cask install dropbox
cask install google-chrome
cask install iterm2
cask install macvim
cask install sublime-text
cask install transmission
cask install virtualbox
cask install vlc
cask install vagrant
cask install skype
cask install github
cask install cyberduck
cask install kobito
cask install keka
cask install wireshark
cask install mamp
cask install mou
cask install alfred
cask install java
cask install intellij-idea-ce
cask install xamarin

tap sanemat/font
install fontforge --with-python
install --powerline --vim-powerline ricty

cleanup
