
# tap repositories and their packages

## Direct install
brew https://raw.github.com/apiaryio/drafter/master/tools/homebrew/drafter.rb

tap argon/mas
brew mas

tap caskroom/cask
cask appcleaner
cask audacity
cask betterzipql
cask bittorrent
cask ccleaner
cask ccmenu
cask charles
cask cyberduck
cask dayone-cli
cask dropbox
cask electrum
cask firefox
cask gitup
cask google-cloud-sdk
cask google-japanese-ime
cask iterm2
cask java
cask karabiner
cask keka
cask kitematic
cask mactex
cask macvim
cask mendeley-desktop
cask mongodb-compass
cask netspot
cask qlcolorcode
cask qlmarkdown
cask qlprettypatch
cask qlstephen
cask quicklook-csv
cask quicklook-json
cask sequel-pro
cask sketch
cask skim
cask skype
cask sqlitebrowser
cask suspicious-package
cask transmission
cask vagrant
cask virtualbox
cask visual-studio-code
cask vlc
cask wireshark
cask xld
cask xquartz

tap codeclimate/formulae
brew codeclimate
cask mactex

tap homebrew/binary

tap homebrew/core
brew ansible
brew argp-standalone
brew arping
brew aspcud
brew atk
brew autoconf
brew automake
brew awscli
brew binutils
brew bison
brew c-ares
brew cadaver
brew cairo
brew cflow
brew cgdb
brew clasp
brew cloc
brew cloog
brew cmake
brew cowsay
brew ctags
brew curl
brew czmq
brew dfc
brew direnv
brew dirmngr
brew doctl
brew doxygen
brew eigen
brew ffmpeg
brew fish
brew flac
brew fltk
brew fluid-synth
brew fondu
brew fontconfig --universal
brew fontforge
brew fortune
brew freetype --universal
brew gd --universal
brew gdb
brew gdbm
brew gdk-pixbuf
brew geoip
brew gettext
brew gibo
brew git
brew glib
brew global
brew gmp
brew gnome-icon-theme
brew gnupg
brew gnupg2
brew gnutls
brew go
brew gobject-introspection
brew gperftools
brew gpg-agent
brew gradle
brew graphviz
brew gringo
brew gsettings-desktop-schemas
brew gsl
brew gtk+
brew gtk+3
brew gtk-mac-integration
brew gtksourceview
brew gtksourceview3
brew harfbuzz
brew haskell-stack
brew hicolor-icon-theme
brew htop-osx
brew httpie
brew httping
brew hub
brew hugo
brew icu4c
brew ilmbase
brew imagemagick
brew intltool
brew iperf
brew ipmitool
brew isl
brew jasper --universal
brew jpeg --universal
brew jpeg-turbo
brew jq
brew keybase
brew lame
brew libao
brew libassuan
brew libcroco
brew libepoxy
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libgphoto2 --universal
brew libicns --universal
brew libksba
brew libmpc
brew libnet
brew libnids
brew libogg
brew libpng --universal
brew librsvg
brew librtlsdr
brew libsodium
brew libsvm
brew libtasn1 --universal
brew libtiff --universal
brew libtool --universal
brew libusb --universal
brew libusb-compat --universal
brew libvorbis
brew libxml2
brew libyaml
brew libzip
brew litmus
brew little-cms2 --universal
brew llvm
brew lorem
brew lua
brew makedepend
brew masscan
brew maven
brew mecab
brew mecab-ipadic
brew mercurial
brew mongodb
brew mpfr
brew mtr
brew mysql
brew nasm
brew neon
brew nettle
brew nkf
brew nmap
brew node
brew ocaml
brew ocamlbuild
brew oniguruma
brew opam
brew open-mpi
brew openexr
brew openssl --universal
brew ossp-uuid
brew pacvim
brew pandoc
brew pango
brew pcre
brew pdflib-lite
brew pdsh
brew peco
brew perl
brew pinentry
brew pixman
brew pkg-config
brew portaudio
brew pssh
brew pstree
brew pth
brew py2cairo
brew pygobject
brew pygobject3
brew pygtk
brew pygtksourceview
brew python
brew python3
brew qemu
brew rarian
brew rbenv
brew readline
brew redis
brew rlwrap
brew ruby
brew ruby-build
brew sane-backends --universal
brew sbt
brew scala
brew scons
brew sdl
brew sdl_net
brew sdl_sound
brew shared-mime-info
brew siege
brew speex
brew sqlite
brew sslscan
brew szip
brew tag
brew the_silver_searcher
brew tig
brew timidity
brew tldr
brew tmux
brew tokyo-cabinet
brew tree
brew typesafe-activator
brew unixodbc
brew unrar
brew utf8proc
brew vim
brew watch
brew wget
brew x264
brew xdot
brew xvid
brew xz
brew youtube-dl
brew zeromq

tap homebrew/dupes
brew libpcap

tap homebrew/games
brew dosbox-x

tap homebrew/php
brew composer
brew php70
brew php70-apcu
brew php70-opcache

tap homebrew/python
brew numpy

tap homebrew/science
brew hdf5
brew opencv

tap homebrew/services

tap homebrew/versions
brew cloog-ppl015
brew cloog018
brew gmp4
brew isl011
brew libmpc08
brew mpfr2
brew ppl011

tap homebrew/versions

tap homebrew/x11
brew openmotif
brew tgif
brew tiger-vnc
brew xpdf

tap neovim/neovim

tap nishanths/tap

tap peco/peco

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty --vim-powerline --powerline

tap tldr-pages/tldr

tap yudai/gotty

# Other Homebrew packages
brew d-bus
brew zmq

# App Store applications
appstore 443987910 1Password
appstore 451732904 App Language Chooser
appstore 458034879 Dash
appstore 409183694 Keynote
appstore 715768417 Microsoft Remote Desktop
appstore 409203825 Numbers
appstore 412347921 OmmWriter
appstore 409201541 Pages
appstore 407963104 Pixelmator
appstore 409789998 Twitter
appstore 415571499 Windows Phone
appstore 497799835 Xcode
appstore 408981381 iPhoto
